In [44]:
# this model is to create a class for the calories per day

class dailylog(object):
    def __init__(self, caloriesB, caloriesL, caloriesD):
        self.caloriesB = caloriesB
        self.caloriesL = caloriesL
        self.caloriesD = caloriesD
        
    def calorie_count(self, totalmaxcal = 1700):
        self.totalmaxcal = totalmaxcal
        self.caltoday = self.caloriesB + self.caloriesL + self.caloriesD
        self.caldiff = abs(self.caltoday - self.totalmaxcal)
        if self.caltoday > self.totalmaxcal:
            return("bluddclart, u need to cut and go gym my guy", self.caltoday, "you've gone over by", self.caldiff, "calories")
        else:
            return("nahh keep eatin u looking skimpy, you've only had", self.caltoday, "cals today")
    



userinput = input("please type in your calories for breakfast lunch and dinner (please seperate by commas):")
B,L,D = userinput.split(",")

Day1 = dailylog(int(B), int(L), int(D))
print(Day1.calorie_count())

please type in your calories for breakfast lunch and dinner (please seperate by commas): 200, 700, 1000

("stop eating u biffta, you've had", 1900, "you've gone over by", 200, 'calories')

In [69]:
## this model is to calculate the either force, mass or acceleration when two of the three are given


class newtons2ndlaw(object):
    def __init__(self, force = None, mass = None, acceleration = None):
        self.force = force
        self.mass = mass
        self.acceleration = acceleration
    def eqns(self):
        if self.force is None:
            self.force = self.mass*self.acceleration
        elif self.mass is None:
             self.mass = self.force/self.acceleration
        elif self.acceleration is None:
            self.acceleration = self.force/self.mass
        return(self.force, self.mass, self.acceleration)
        
missing = input("what do you want to calculate (force/mass/acceleration):")
userinput = input("please add the values of the others")

val1, val2 = userinput.split(",")



if missing == "force":
    Equation1 = newtons2ndlaw(force = None, mass = float(val1), acceleration = float(val2))
    print("the force is:", Equation1.eqns()[0])
elif missing == "mass":
    Equation1 = newtons2ndlaw(force = float(val1), mass = None, acceleration = float(val2))
    print("the mass is:", Equation1.eqns()[1])
elif missing == "acceleration":
    Equation1 = newtons2ndlaw(force = float(val1), mass = float(val2), acceleration = None)
    print("the acceleration is:", Equation1.eqns()[2])

what do you want to calculate (force/mass/acceleration): mass
please add the values of the others 2.56,4.97

the mass is: 0.5150905432595574

In [ ]:
##this model finds if all the instances of a word in a sentence using regular expression:
import re
userinput = input("please type a sentence:")
word = input("what word would you like to count:")

result = re.findall(word, userinput) ###instead of using RegEx, you can also just use result = userinput.count(word)

print("in the sentence:", userinput, "the word", word, "appears:", len(result), "times")

In [ ]:
## This model open a file and reads certain amount of characters

with open(example1, "r") as file1:
    print(file1.read(16))
    print(file1.read(5))
    print(file1.read(9))



# Read all lines and save as a list

with open(example1, "r") as file1:
    FileasList = file1.readlines()
    
# Print the first line
FileasList[0]
# Print the second line
FileasList[1]
# Print the third line
FileasList[2]

In [ ]:
##this model open a file to write in:
with open(example2,"w") as writefile:
    lines =["this is line A\n","this is line B\n", "this is line c\n"]
    for line in lines:
        file1.write(line)

## this will make:
##this is line A
##this is line B
##this is line C

In [26]:
##this code block is going throught data frames and accessing elements:

##making a data frame out of a dictionary:
!pip install pandas
import pandas as pd
##dictionary:
x = {"name": ["rose", "john", "jane", "mary"], "ID": [1,2,3,4], "Job role": ["architect","software","design","infrastructure"], "salary": [100000, 80000, 50000,60000]}
##dictionary to data frame:
df = pd.DataFrame(x)
df

x = df[["ID"]]
x

z = df[["name", "Job role", "salary"]]
z


x = df["name"]  ##using one bracket just makes it into a series
x

df2=df
df2=df2.set_index("name") ## creating a new data frame, and setting the name column as an index
df2

#To display the first 5 rows of new dataframe
df2.head()

#finding jane's department:
df2.loc['jane', 'Job role']

#finding mary's salary:
df2.loc["mary", "salary"]

##slicing:
df.iloc[0:2, 0:3]

##slicing using loc() function on new dataframe df2 where index column is Name having labels: Rose, John and Jane
df2.loc['rose':'jane', 'ID':'Job role']

Requirement already satisfied: pandas in c:\users\sethl\jupyter\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sethl\jupyter\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

      ID   Job role
name
rose   1  architect
john   2   software
jane   3     design

In [57]:
###intro into pandas:

import pandas as pd
# Read data from CSV file


df = pd.read_csv(r"C:\Users\sethl\Downloads\Product_sales.csv")
df.head() ## this prints the first 5 rows

x = df[["Quantity"]]
x ## this gives the quantity column in a data frame and assigns it to x

y = df["Product"]
y ## this gives product as a series


z = df[["Quantity", "Price", "Total"]]
z ## this selects multiple colums and creates another data frame


df.iloc[0,0] ##gives first column and first row element
df.iloc[2,3] ## gives 3rd row and 4th column

df.loc[0, "Product"] ##column access using name

df.iloc[0:2,0:3] ## slicing to create the first 2rows and first 3columns
df.iloc[0:5,0:8]

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [83]:
###working with numpy 1D:

import numpy as np

c = np.array([20,1,2,3,4])

##printing the even digits of the array arr
arr = np.array([1,2,3,4,5,6,7,8])

#print(arr[1:9:2])
a = np.array([0, 1, 2, 3, 4])

u =np.array([1,0])
v =np.array([0,1])

b = np.add(u,v)
b


###Convert the list [1, 2, 3] and [8, 9, 10] to numpy arrays arr1 and arr2. 
#Then perform Addition , Subtraction , Multiplication , Division and Dot Operation on the arr1 and arr2.

arr1 = np.array([1,2,3])
arr2 = np.array([8,9,10])
##addition:
x = np.add(arr1,arr2)
##subtraction:
z = np.subtract(arr1,arr2)
##multiplication:
M = np.multiply(arr1,arr2)
##Division:
D = np.divide(arr1,arr2)
##dot product:
P = np.dot(arr1,arr2)
##############################




##Convert the list [1, 2, 3, 4, 5] and [6, 7, 8, 9, 10] to numpy arrays arr3 and arr4. Then find the even and odd numbers from arr1 and arr2.
arr3 = np.array([1,2,3,4,5])
arr4 = np. array([6,7,8,9,10])
print("the even numbers from arr3 are:", arr3[1:6:2], "& the even numbers from arr4 are:", arr4[0:6:2])
print("the odd numbers from arr3 are:", arr3[0:6:2], "& the odd numbers from arr4 are:", arr4[1:6:2])

the even numbers from arr3 are: [2 4] & the even numbers from arr4 are: [ 6  8 10]
the odd numbers from arr3 are: [1 3 5] & the odd numbers from arr4 are: [7 9]

In [84]:
##2D numpys & matricies:

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)

b = [[0, 1], [1, 0], [1, 1], [-1, 0]]
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

C = np.dot(A,B) ##matrix multiplication
C

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

In [94]:
###API testing:
##webscraping:

import requests
from bs4 import BeautifulSoup
# Specify the URL of the webpage you want to scrape
url = 'https://en.wikipedia.org/wiki/IBM'
##get request:
response = requests.get(url)
# Store the HTML content in a variable
html_content = response.text
# Create a BeautifulSoup object to parse the HTML
soup = BeautifulSoup(html_content, 'html.parser')

# Display a snippet of the HTML content
print(html_content[:500])

# Find all <a> tags (anchor tags) in the HTML
links = soup.find_all('a')

# Iterate through the list of links and print their text
for link in links:
    print(link.text)

Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.

In [104]:
import requests
import os 
from PIL import Image
from IPython.display import IFrame

##get request to ibm.com:

url='https://www.ibm.com/'
r=requests.get(url)
##We have the response object r, 
#this has information about the request, like the status of the request. We can view the status code using the attribute status_code.
r.status_code


##view request headers:
print(r.request.headers)
##view request body:
print("request body:", r.request.body)

##This returns a python dictionary of HTTP response headers.
header=r.headers
print(r.headers)
##date and content type check
header['Date']
header['Content-Type']
##encoding check
r.encoding
##review the first 100 characters
r.text[0:100]

url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/IDSNlogo.png'

{'User-Agent': 'python-requests/2.32.5', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '_abck=DA23FA06213957322CF4E177D57799ED~-1~YAAQXB4SAmJrZridAQAABxfxvw/gEuOkQP51Fhv+vx4BKsDLmhjV5XSZNAWg9GIZbxT3KnBofp7NJSOHb//kWEAUdXzy399Azg/tiAeXxuRo7yYTew5LUCMd6/S8dLhNp90AMsUO8nQKmLa71iFe+rIp486pG9TH53mODd89NOseDrRlFmg9qNm5UvzCGThcmWUjtX7BzY98UHHfwv8LtaSJART8Cf/ZjViZ9nawf5VeY1wZR1r4YZdhhyuBLLM156GKzJ5pq9jye5JVXlVe8sSwCN8knCjr1HSiyfBL6XF6wWrPuIkmCg+LSLZCVxjmNs+CmFk0FFVFS4+arDifH+7vzJ+raBkkxM4U1J9duEhZHFxwwSsG8MkpAtfarPPQ62lbPC2OeKtKu5HnW7n+PG0VA6ZfPTjwn+KC1PDf0xM1qM15VCmlvPmWfYD1AtdEsQA=~-1~-1~-1~-1~-1; bm_sz=C914D6BC43988726327A3879490BAED4~YAAQXB4SAmRrZridAQAABxfxvx83JNDh/5NUjKqZEC62zgCcX5ym8LttYGbzrqf9jrIXoon8/ZRf5/XDn9zBgciHxyfHOih7H5iMXP5m97twmwt8FjetywP63/x04OREG1WVH7EYVpu0n+VZq8s8hVrpDTslTxrJNWUcisLVGc8C3q4j23pGbgo2Kcdu3+VQFdESqDKfsjnCXHlJwYVzQFOqXlZMqJBKqOz1grxY9JCJmTL6a2M89iaLJMfNUvdjfSc1kceB0zhbrhT4HeoTWseodYxd+ESZs5+ImShHzzLTmGIbWkCX/W0/N3rZppGm0HCtnAawBEnQHIeyO4ypc2FZg0SJA/k=~4404546~4273202'}
request body: None
{'Content-Security-Policy': 'upgrade-insecure-requests', 'x-frame-options': 'SAMEORIGIN', 'Last-Modified': 'Fri, 24 Apr 2026 14:35:31 GMT', 'ETag': 'W/"2fd7b-65035ad4ca13c-gzip"', 'Accept-Ranges': 'bytes', 'Content-Type': 'text/html;charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'max-age=600', 'Expires': 'Fri, 24 Apr 2026 14:52:22 GMT', 'X-Akamai-Transformed': '0 - 0 -', 'Content-Encoding': 'gzip', 'Date': 'Fri, 24 Apr 2026 14:42:22 GMT', 'Content-Length': '39209', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=31536000'}

In [110]:
##URL = <https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Example1.txt
###code to download the data from this url:

url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Example1.txt'

path = os.path.join(os.getcwd(),'example1.txt') ##spcifing file path and name
r = requests.get(url)

with open(path,'wb') as f: ## saving content with open and write method
    f.write(r.content)

In [127]:
##GET REQUEST with a url:

url_get='http://httpbin.org/get' ##append the url with /get (get request)
payload = {"name:": "Joseph", "ID:":"123"} ## Query string (name and parameters)
r = requests.get(url_get, params = payload) ## passing the dictionary(payload) to the parameters of the get function
r.url ## this prints out the url

print("request body:", r.request.body) ## prints out the request body (None)
print(r.status_code) ## prints status code (200)
print(r.text) ## prints out response as text

r.headers['Content-Type'] ## prints the content type (JSON format)
r.json() ## as content is in JSON format, we can view it in python using r.json() to view as a dictionary in python
r.json()['args'] ##we can now view the name and values


##POST REQUEST with a url:

url_post='http://httpbin.org/post' ## append with post
r_post = requests.post(url_post, data = payload)## passing the dictionary(payload) to the parameters of the post function

print("POST request URL:",response.url )## prints post url
print("GET request URL:",r.url) ## prints get url

print("POST request body:",r_post.request.body) ## comparing the body of the post vs the get: (only post has a body)
print("GET request body:",r.request.body)


r_post.json()['form']  ##viewing the form:

request body: None
200
{
  "args": {
    "ID:": "123",
    "name:": "Joseph"
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.32.5",
    "X-Amzn-Trace-Id": "Root=1-69f21997-0ffb9d827a08545e60b9a35a"
  },
  "origin": "82.36.104.3",
  "url": "http://httpbin.org/get?name%3A=Joseph&ID%3A=123"
}

POST request URL: https://en.wikipedia.org/wiki/IBM
GET request URL: http://httpbin.org/get?name%3A=Joseph&ID%3A=123
POST request body: name%3A=Joseph&ID%3A=123
GET request body: None

{'ID:': '123', 'name:': 'Joseph'}

In [139]:
##Load and use RandomUser API, using RandomUser() Python library

!pip install randomuser
!pip install pandas
from randomuser import RandomUser
import pandas as pd

r = RandomUser() ## creating a random user object

some_list = r.generate_users(10) ## this generates a list of 10 random users:
some_list

name = r.get_full_name() ## using one of the get methods, we cen get the names:

## to make a list of the 10 random users: names and email addresses:
for user in some_list:
    print(user.get_full_name(), " ", user.get_email()) ##for loop to print out the 10 names and emails:

for user in some_list:
    print(user.get_picture()) ## generating photos of the users

##generating a table of information about the users using a function:
def get_users():
    users = []
    
    for user in RandomUser.generate_users(10):
        users.append({"Name": user.get_full_name(),"Gender:": user.get_gender(), "City:": user.get_city(), "State:": user.get_state(), "Email:": user.get_email(), "DOB:": user.get_dob(), "Picture:": user.get_picture()})
    return pd.DataFrame(users)
get_users()

df1 = pd.DataFrame(get_users()) ## we now have a pandas dataframe of the users

Requirement already satisfied: randomuser in c:\users\sethl\jupyter\lib\site-packages (1.6)
Requirement already satisfied: pandas in c:\users\sethl\jupyter\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sethl\jupyter\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Edouard Leclerc   edouard.leclerc@example.com
Ümit Aclan   umit.aclan@example.com
Lotte Helgheim   lotte.helgheim@example.com
Daniela Ruiz   daniela.ruiz@example.com
Helen Dumas   helen.dumas@example.com
Roy Franklin   roy.franklin@example.com
Felix Chapman   felix.chapman@example.com
Remedios Perez   remedios.perez@example.com
Suleni Ferreira   suleni.ferreira@example.com
Eleonora Gäbler   eleonora.gabler@example.com
https://randomuser.me/api/portraits/men/14.jpg
https://randomuser.me/api/portraits/men/93.jpg
https://randomuser.me/api/portraits/women/1.jpg
https://randomuser.me/api/portraits/women/75.jpg
https://randomuser.me/api/portraits/women/23.jpg
https://randomuser.me/api/portraits/men/48.jpg
https://randomuser.me/api/portraits/men/86.jpg
https://randomuser.me/api/portraits/women/41.jpg
https://randomuser.me/api/portraits/women/92.jpg
https://randomuser.me/api/portraits/women/80.jpg

In [156]:
##Fruityvice API - this gives information about many fruits:

#importing librarys:
import requests
import json
import pandas as pd

#We will obtain the fruityvice API data using requests.get("url") function
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")
#retrieve results using json.loads() function.
results = json.loads(data.text)
#creating a pandas date frame:
pd.DataFrame(results)
##normalizing the data (as column contains multiple subcolumns)
df2 = pd.json_normalize(results)
df2
## Extracting data: e.g. cherry family and genus
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus']) ## returns Rosaceae & Prunus

## Extracting the data of calories in a banana:
banana = df2.loc[df2["name"] == 'Banana']
(banana.iloc[0]['nutritions.calories']) ## returns 96

## extracting the macros of a watermelon:
watermelon = df2.loc[df2["name"] == "Watermelon"]
print("the macros of a watermelon are as follows:", "calories:",(watermelon.iloc[0]['nutritions.calories']), "fat:",(watermelon.iloc[0]['nutritions.fat']), "sugar:", (watermelon.iloc[0]['nutritions.sugar']), "carbs:",(watermelon.iloc[0]['nutritions.carbohydrates']), "protein:", (watermelon.iloc[0]['nutritions.protein']))

the macros of a watermelon are as follows: calories: 30 fat: 0.2 sugar: 6.0 carbs: 8.0 protein: 0.6

In [162]:
##official joke API:
import requests
import json
import pandas as pd

data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")
results2 = json.loads(data2.text)
pd.DataFrame(results2)
##Convert json data into pandas data frame. Drop the type and id columns.
df3 = pd.json_normalize(results2)
df3.drop(columns =["type","id"], inplace = True)
df3

,setup,punchline
0,What do you give to a lemon in need?,Lemonaid.
1,Did you hear about the Mexican train killer?,He had loco motives
2,Why couldn't the bicycle stand up by itself?,It was two-tired.
3,How do hens stay fit?,They always egg-cercise!
4,Where do hamburgers go to dance?,The meat-ball.
5,Did you hear about the runner who was criticized?,He just took it in stride
6,Do you know what the word 'was' was initially?,Before was was was was was is.
7,What do you do on a remote island?,Try and find the TV island it belongs to.
8,Why did the octopus beat the shark in a fight?,Because it was well armed.
9,Why did the barber win the race?,He took a short cut.

In [164]:
##web scraping using python: (BeautifulSoup)

from bs4 import BeautifulSoup
import requests
URL = "http://www.example.com"
page = requests.get(URL)
soup = BeautifulSoup(page.content, "html.parser")

##webscraping using scrapy

import scrapy
class QuotesSpider(scrapy.Spider):
    name = "quotes"
    start_urls = ['http://quotes.toscrape.com/tag/humor/',]
    def parse(self, response):
        for quote in response.css('div.quote'):
            yield {'quote': quote.css('span.text::text').get()}


##webscraping using selenium

from selenium import webdriver
driver = webdriver.Firefox()
driver.get("http://www.example.com")

In [183]:
!pip install bs4
!pip install requests pandas
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page

## html example stored as a string:
html="<!DOCTYPE html><html><head><title>Page Title</title></head><body><h3><b id='boldest'>Lebron James</b></h3><p> Salary: $ 92,000,000 </p><h3> Stephen Curry</h3><p> Salary: $85,000, 000 </p><h3> Kevin Durant </h3><p> Salary: $73,200, 000</p></body></html>"
## to break down the document into a nested structure:
soup = BeautifulSoup(html, 'html.parser')
print(soup.prettify()) ## method prettify() to display the HTML in the nested structure

##Let's say we want the title of the page and the name of the top paid player. We can use the Tag.
tag_object = soup.title
print("tag object", tag_object)
print("tag object type:", type(tag_object))
tag_object=soup.h3
tag_object
##Enclosed in the bold attribute .b, it helps to use the tree representation. We can navigate down the tree using the child attribute to get the name.
##As stated above, the Tag object is a tree of objects. We can access the child of the tag or navigate down the branch as follows:
tag_child = tag_object.b
tag_child

#You can access the parent with the .parent
tag_parent = tag_child.parent
tag_parent

sibling_1=tag_object.next_sibling
sibling_1

sibling_2=sibling_1.next_sibling
sibling_2

sibling_3 = sibling_2.next_sibling
sibling_3

tag_child['id'] ##the tag id="boldest" has an attribute id whose value is boldest. treat the tag like a dictionary:
tag_child.attrs ##You can access that dictionary directly as attrs:
tag_child.get('id') #We can also obtain the content of the attribute of the tag using the Python get() method.


tag_string=tag_child.string ##A string corresponds to a bit of text or content within a tag
tag_string # In our HTML we can obtain the name of the first player by extracting the string of the Tag object tag_child

unicode_string = str(tag_string)
unicode_string

Requirement already satisfied: bs4 in c:\users\sethl\jupyter\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\sethl\jupyter\lib\site-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\sethl\jupyter\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sethl\jupyter\lib\site-packages (from beautifulsoup4->bs4) (4.15.0)
Requirement already satisfied: requests in c:\users\sethl\jupyter\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\users\sethl\jupyter\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sethl\jupyter\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sethl\jupyter\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sethl\jupyter\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sethl\jupyter\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sethl\jupyter\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
<!DOCTYPE html>
<html>
 <head>
  <title>
   Page Title
  </title>
 </head>
 <body>
  <h3>
   <b id="boldest">
    Lebron James
   </b>
  </h3>
  <p>
   Salary: $ 92,000,000
  </p>
  <h3>
   Stephen Curry
  </h3>
  <p>
   Salary: $85,000, 000
  </p>
  <h3>
   Kevin Durant
  </h3>
  <p>
   Salary: $73,200, 000
  </p>
 </body>
</html>

tag object <title>Page Title</title>
tag object type: <class 'bs4.element.Tag'>

'Lebron James'

In [197]:
!pip install bs4
!pip install requests pandas
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page

#Filters allow you to find complex patterns, the simplest filter is a string. 
#In this section we will pass a string to a different filter method and Beautiful Soup will perform a match against that exact string. 
##We can store it as a string in the variable table:
table="<table><tr><td id='flight'>Flight No</td><td>Launch site</td> <td>Payload mass</td></tr><tr> <td>1</td><td><a href='https://en.wikipedia.org/wiki/Florida'>Florida<a></td><td>300 kg</td></tr><tr><td>2</td><td><a href='https://en.wikipedia.org/wiki/Texas'>Texas</a></td><td>94 kg</td></tr><tr><td>3</td><td><a href='https://en.wikipedia.org/wiki/Florida'>Florida<a> </td><td>80 kg</td></tr></table>"
table_bs = BeautifulSoup(table, "html.parser")
##The find_all() method looks through a tag’s descendants and retrieves all descendants that match your filters.
#The Method signature for find_all(name, attrs, recursive, string, limit, **kwargs)
table_rows = table_bs.find_all('tr')
table_rows
first_row =table_rows[0]
first_row
print(type(first_row))
first_row.td

#If we iterate through the list, each element corresponds to a row in the table:
for i, row in enumerate(table_rows):
    print("row", i , "is", row)

#As row is a cell object, we can apply the method find_all to it and extract table cells in the object cells using the tag td, 
#this is all the children with the name td. 
#The result is a list, each element corresponds to a cell and is a Tag object, we can iterate through this list as well. 
#We can extract the content using the string attribute.
for i, row in enumerate(table_rows):
    print("row", i)
    cells = row.find_all("td")
    for j, cell in enumerate(cells):
        print('colunm',j,"cell",cell)

list_input = table_bs.find_all(name = ["tr","td"]) ##If we use a list we can match against any item in that list.
list_input


##If the argument is not recognized it will be turned into a filter on the tag’s attributes. 
#For example with the id argument, Beautiful Soup will filter against each tag’s id attribute. 
#For example, the first td elements have a value of id of flight, therefore we can filter based on that id value.
table_bs.find_all(id = "flights")
list_input=table_bs.find_all(href="https://en.wikipedia.org/wiki/Florida") #We can find all the elements that have links to the Florida Wikipedia page:
list_input
table_bs.find_all(href=True)

#With string you can search for strings instead of tags, where we find all the elments with Florida:
table_bs.find_all(string="Florida")

Requirement already satisfied: bs4 in c:\users\sethl\jupyter\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\sethl\jupyter\lib\site-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\sethl\jupyter\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sethl\jupyter\lib\site-packages (from beautifulsoup4->bs4) (4.15.0)
Requirement already satisfied: requests in c:\users\sethl\jupyter\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\users\sethl\jupyter\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sethl\jupyter\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sethl\jupyter\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sethl\jupyter\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sethl\jupyter\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sethl\jupyter\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
<class 'bs4.element.Tag'>
row 0 is <tr><td id="flight">Flight No</td><td>Launch site</td> <td>Payload mass</td></tr>
row 1 is <tr> <td>1</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a></a></a></td><td>300 kg</td></tr>
row 2 is <tr><td>2</td><td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td><td>94 kg</td></tr>
row 3 is <tr><td>3</td><td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a> </a></a></td><td>80 kg</td></tr>
row 0
colunm 0 cell <td id="flight">Flight No</td>
colunm 1 cell <td>Launch site</td>
colunm 2 cell <td>Payload mass</td>
row 1
colunm 0 cell <td>1</td>
colunm 1 cell <td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a></a></a></td>
colunm 2 cell <td>300 kg</td>
row 2
colunm 0 cell <td>2</td>
colunm 1 cell <td><a href="https://en.wikipedia.org/wiki/Texas">Texas</a></td>
colunm 2 cell <td>94 kg</td>
row 3
colunm 0 cell <td>3</td>
colunm 1 cell <td><a href="https://en.wikipedia.org/wiki/Florida">Florida<a> </a></a></td>
colunm 2 cell <td>80 kg</td>

In [202]:
##Downloading And Scraping The Contents Of A Web Page:
!pip install bs4
!pip install requests pandas
from bs4 import BeautifulSoup
import requests

url = "http://www.ibm.com"
data = requests.get(url).text
soup = BeautifulSoup(data, "html.parser") # create a soup object using the variable 'data'
#Scrape all links
for link in soup.find_all("a", href = True): # in html anchor/link is represented by the tag <a>
    print(link.get('href'))

#scraping all image tags:
for link in soup.find_all("img"): # in html image is represented by the tag <img>
    print(link)
    print(link.get("src"))

Requirement already satisfied: bs4 in c:\users\sethl\jupyter\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\sethl\jupyter\lib\site-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\sethl\jupyter\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sethl\jupyter\lib\site-packages (from beautifulsoup4->bs4) (4.15.0)
Requirement already satisfied: requests in c:\users\sethl\jupyter\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\users\sethl\jupyter\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sethl\jupyter\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sethl\jupyter\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sethl\jupyter\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sethl\jupyter\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sethl\jupyter\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
https://bob.ibm.com/?lnk=hpls1uk
https://www.ibm.com/events/think?lnk=hpls2uk
https://www.ibm.com/forms/webinars/mkt-webinar-24771?lnk=hprc1uk
https://www.ibm.com/forms/mkt-169e6?lnk=hprc2uk
https://ibm.briefingsource.com/register/U9Y8DFW2?lnk=hprc3uk
https://www.ibm.com/forms/mkt-53811?lnk=hprc4uk
https://www.ibm.com/sports/ferrari?lnk=hpcs1uk
https://www.ibm.com/case-studies/avid-solutions-international?lnk=hpcs2us
https://www.ibm.com/case-studies/pfizer?lnk=hpcs3us
https://www.ibm.com/software?lnk=hpfp1us
https://www.ibm.com/solutions/ai-agents?lnk=hpfp2us
https://www.ibm.com/solutions/data-and-ai?lnk=hpfp3us
https://www.ibm.com/solutions/automation?lnk=hpfp4us
https://www.ibm.com/solutions/hybrid-cloud?lnk=hpfp5us
https://www.ibm.com/solutions/ai-models?lnk=hpfp6us
https://www.ibm.com/solutions/analytics?lnk=hpfp7us
https://www.ibm.com/solutions/security?lnk=hpfp8us
https://www.ibm.com/consulting?lnk=hpfp9us
https://www.ibm.com/uk-en/about?lnk=hpii1uk
https://www.ibm.com/history?lnk=hpii1us
https://research.ibm.com?lnk=hpii1us
https://www.ibm.com/quantum?lnk=hpii1us
https://www.ibm.com/careers?lnk=hpii1us
https://skillsbuild.org?lnk=hpii1us
https://uk.newsroom.ibm.com/ibm-and-pearson-collaborate-to-build-new-ai-powered-learning-tools
https://uk.newsroom.ibm.com/announcements?item=122900
https://uk.newsroom.ibm.com/ibm-2026-x-force-threat-index
https://uk.newsroom.ibm.com/announcements?item=122898
https://uk.newsroom.ibm.com/ibm-report-ai-to-drive-revenue-by-2030-but-reskilling-and-integration-critical-to-uk-growth
https://uk.newsroom.ibm.com/announcements?item=122896
https://uk.newsroom.ibm.com/ibm-introduces-new-software-to-address-growing-digital-sovereignty-imperative
https://uk.newsroom.ibm.com/ibm-announces-long-term-renewal-as-the-official-ai-cloud-and-digital-transformation-partner-for-aeltc
<img alt="Abstract Overlapping Color Glass" class="cmp-image__image" height="1200" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/concert_dco_native_04-1?ts=1777383669519&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Abstract geometric design with soft gradients" width="1200"/>
https://assets.ibm.com/is/image/ibm/concert_dco_native_04-1?ts=1777383669519&dpr=off
<img alt="Abstract Overlapping Color Glass" class="cmp-image__image" height="1200" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/concert_dco_native_01-1?ts=1777383638707&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Colorful transparent discs in abstract arrangement" width="1200"/>
https://assets.ibm.com/is/image/ibm/concert_dco_native_01-1?ts=1777383638707&dpr=off
<img alt="Abstract Overlapping Color Glass" class="cmp-image__image" height="1200" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/sec_li1?ts=1777383679193&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Abstract geometric pattern with colorful accents" width="1200"/>
https://assets.ibm.com/is/image/ibm/sec_li1?ts=1777383679193&dpr=off
<img alt="Abstract Overlapping Color Glass" class="cmp-image__image" height="319" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/ai-agent-single-1x1?ts=1777383568204&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Minimal purple square object on tiled wall" width="319"/>
https://assets.ibm.com/is/image/ibm/ai-agent-single-1x1?ts=1777383568204&dpr=off
<img alt="Ferrari logo" class="cmp-image__image" height="1920" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/ferrari-shield-transparent?ts=1775571364568&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Ferrari emblem with prancing horse design" width="3840"/>
https://assets.ibm.com/is/image/ibm/ferrari-shield-transparent?ts=1775571364568&dpr=off
<img alt="Avid Solutions logo" class="cmp-image__image" height="160" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/avid-solutions?ts=1772789856280&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Avid Solutions Text with Orange Feather Graphic" width="320"/>
https://assets.ibm.com/is/image/ibm/avid-solutions?ts=1772789856280&dpr=off
<img alt="Pfizer logo" class="cmp-image__image" height="2591" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/pfizer_logo-1?ts=1770666368541&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" width="6276"/>
https://assets.ibm.com/is/image/ibm/pfizer_logo-1?ts=1770666368541&dpr=off
<img alt="2026 Scuderia Ferrari HP Formula 1 race car, rear view" class="cmp-image__image" height="3840" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/f678_still_f06_v10_zyn_4096x4096?ts=1775559808648&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Rear view of Formula 1 race car with IBM logo" width="3840"/>
https://assets.ibm.com/is/image/ibm/f678_still_f06_v10_zyn_4096x4096?ts=1775559808648&dpr=off
<img alt="Female looking over plants with Avid Solutions logo" class="cmp-image__image" height="1468" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/avid-solutions-leadspace?ts=1772789949750&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Indoor hydroponic garden with lush greenery" width="3840"/>
https://assets.ibm.com/is/image/ibm/avid-solutions-leadspace?ts=1772789949750&dpr=off
<img alt="Pfizer + IBM logos over 3d render of blue molecules" class="cmp-image__image" height="2160" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/pfizer_thumb?ts=1770676313341&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" title="Pfizer and IBM collaboration visual concept" width="3840"/>
https://assets.ibm.com/is/image/ibm/pfizer_thumb?ts=1770676313341&dpr=off
<img alt="Illustration of an eye with connecting lines to data" class="cmp-image__image" height="2961" itemprop="contentUrl" loading="lazy" src="https://assets.ibm.com/is/image/ibm/watson-discovery_eye-connection_1x1_padding?ts=1768982912247&amp;dpr=off" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" width="2961"/>
https://assets.ibm.com/is/image/ibm/watson-discovery_eye-connection_1x1_padding?ts=1768982912247&dpr=off

In [205]:
#Scrape data from HTML tables
!pip install bs4
!pip install requests pandas
from bs4 import BeautifulSoup
import requests
##The below url contains an html table with data about colors and color codes.
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/HTMLColorCodes.html"
# get the contents of the webpage in text format and store in a variable called data
data = requests.get(url).text
soup = BeautifulSoup(data, "html.parser")
#find a html table in the web page:
table = soup.find("table")
#Get all rows from the table:
for row in table.find_all("tr"): # in html table row is represented by the tag <tr>
    # Get all columns in each row.
    cols =row.find_all("td") # in html a column is represented by the tag <td>
    colour_name = cols[2].string# store the value in column 3 as color_name
    colour_code = cols[3].string # store the value in column 4 as color_code
    print("{}--->{}".format(colour_name, colour_code))

Requirement already satisfied: bs4 in c:\users\sethl\jupyter\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\sethl\jupyter\lib\site-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\sethl\jupyter\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sethl\jupyter\lib\site-packages (from beautifulsoup4->bs4) (4.15.0)
Requirement already satisfied: requests in c:\users\sethl\jupyter\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\users\sethl\jupyter\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sethl\jupyter\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sethl\jupyter\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sethl\jupyter\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sethl\jupyter\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sethl\jupyter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sethl\jupyter\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Color Name--->None
lightsalmon--->#FFA07A
salmon--->#FA8072
darksalmon--->#E9967A
lightcoral--->#F08080
coral--->#FF7F50
tomato--->#FF6347
orangered--->#FF4500
gold--->#FFD700
orange--->#FFA500
darkorange--->#FF8C00
lightyellow--->#FFFFE0
lemonchiffon--->#FFFACD
papayawhip--->#FFEFD5
moccasin--->#FFE4B5
peachpuff--->#FFDAB9
palegoldenrod--->#EEE8AA
khaki--->#F0E68C
darkkhaki--->#BDB76B
yellow--->#FFFF00
lawngreen--->#7CFC00
chartreuse--->#7FFF00
limegreen--->#32CD32
lime--->#00FF00
forestgreen--->#228B22
green--->#008000
powderblue--->#B0E0E6
lightblue--->#ADD8E6
lightskyblue--->#87CEFA
skyblue--->#87CEEB
deepskyblue--->#00BFFF
lightsteelblue--->#B0C4DE
dodgerblue--->#1E90FF

In [ ]:
##Different File Formats:
##CSV
import piplite
await piplite.install(['seaborn', 'lxml', 'openpyxl'])

import pandas as pd
from pyodide.http import pyfetch

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/addresses.csv"

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

await download(filename, "addresses.csv")

df = pd.read_csv("addresses.csv", header=None)

##XLSX:
# Not needed unless you're running locally
# import urllib.request
# urllib.request.urlretrieve("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/file_example_XLSX_10.xlsx", "sample.xlsx")

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/file_example_XLSX_10.xlsx"

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

await download(filename, "file_example_XLSX_10.xlsx")

df = pd.read_excel("file_example_XLSX_10.xlsx")


##XML:
import xml.etree.ElementTree as ET

# create the file structure
employee = ET.Element('employee')
details = ET.SubElement(employee, 'details')
first = ET.SubElement(details, 'firstname')
second = ET.SubElement(details, 'lastname')
third = ET.SubElement(details, 'age')
first.text = 'Shiv'
second.text = 'Mishra'
third.text = '23'

# create a new XML file with the results
mydata1 = ET.ElementTree(employee)
# myfile = open("items2.xml", "wb")
# myfile.write(mydata)
with open("new_sample.xml", "wb") as files:
    mydata1.write(files)

# Not needed unless running locally
# !wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Sample-employee-XML-file.xml

import xml.etree.ElementTree as etree

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Sample-employee-XML-file.xml"

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

await download(filename, "Sample-employee-XML-file.xml")
# Parse the XML file
tree = etree.parse("Sample-employee-XML-file.xml")

# Get the root of the XML tree
root = tree.getroot()

# Define the columns for the DataFrame
columns = ["firstname", "lastname", "title", "division", "building", "room"]

# Initialize an empty DataFrame
datatframe = pd.DataFrame(columns=columns)

# Iterate through each node in the XML root
for node in root:
    # Extract text from each element
    firstname = node.find("firstname").text
    lastname = node.find("lastname").text
    title = node.find("title").text
    division = node.find("division").text
    building = node.find("building").text
    room = node.find("room").text
    
    # Create a DataFrame for the current row
    row_df = pd.DataFrame([[firstname, lastname, title, division, building, room]], columns=columns)
    
    # Concatenate with the existing DataFrame
    datatframe = pd.concat([datatframe, row_df], ignore_index=True)

# Here in xpath we mention the set of xml nodes to be considered for migrating  to the dataframe which in this case is details node under employees.
df=pd.read_xml("Sample-employee-XML-file.xml", xpath="/employees/details")

In [ ]:
# importing PIL 
from PIL import Image 

# Uncomment if running locally
# import urllib.request
# urllib.request.urlretrieve("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg", "dog.jpg")

filename = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg"

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

await download(filename, "./dog.jpg")
# Read image 
img = Image.open('./dog.jpg','r') 
  
# Output Images 
img.show()

In [208]:
###DATA ANALYSIS:
import pandas as pd
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/diabetes.csv"

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

await download(filename, "diabetes.csv")
df = pd.read_csv("diabetes.csv")
# show the first 5 rows using dataframe.head() method
print("The first 5 rows of the dataframe") 
df.head(5)
df.shape # view the dimensions of the dataframe
df.info() #This method prints information about a DataFrame including the index dtype and columns, non-null values and memory usage.
df.describe() #Pandas describe() is used to view some basic statistical details like percentile, mean, standard deviation, etc. 
#of a data frame or a series of numeric values. When this method is applied to a series of strings, it returns a different output

NameError: name 'pyfetch' is not defined